version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: shortener_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: shortener_adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: shortener_jaeger
    restart: always
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14268:14268'
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: '0.0.0.0:9411'

volumes:
  postgres_data:
    driver: local
